[JuiceAgent]
Version = 1

[JuiceAgent.Loader]
# Path to JuiceAgent-API jar, leave empty to use the built-in API
JuiceAgentAPIJarPath = ""
# Path to libagent.dll, default is "./libagent.dll"
JuiceAgentNativeLibraryPath = ""

[JuiceAgent.Modules]

[JuiceAgent.Modules.JarLoader]
Enabled = true
# Directory containing dependency JARs to load into the JVM (put your deps here)
InjectionDir = "./injection"
# Path to the injection JAR to be loaded
JarPath = "./playload.jar"
# Entry class to be executed after loading the JAR
EntryClass = "playload"
# Entry method, must be: public static void run()
EntryMethod = "entry"
