/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceremapper_JuiceRemapper */

#ifndef _Included_cn_xiaozhou233_juiceremapper_JuiceRemapper
#define _Included_cn_xiaozhou233_juiceremapper_JuiceRemapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    initNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_initNative
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    addInclude
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_addInclude
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    addExclude
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_addExclude
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    removeInclude
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_removeInclude
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    removeExclude
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_removeExclude
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    clearIncludes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_clearIncludes
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    clearExcludes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_clearExcludes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
