/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceagent_api_JuiceAgent */

#ifndef _Included_cn_xiaozhou233_juiceagent_api_JuiceAgent
#define _Included_cn_xiaozhou233_juiceagent_api_JuiceAgent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_init
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    addToBootstrapClassLoaderSearch
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_addToBootstrapClassLoaderSearch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    addToSystemClassLoaderSearch
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_addToSystemClassLoaderSearch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    addToClassLoader
 * Signature: (Ljava/lang/String;Ljava/lang/ClassLoader;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_addToClassLoader
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    defineClass
 * Signature: (Ljava/lang/ClassLoader;[B)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_defineClass
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    redefineClass
 * Signature: (Ljava/lang/Class;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_redefineClass
  (JNIEnv *, jclass, jclass, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    redefineClassByName
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_redefineClassByName
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    retransformClass
 * Signature: (Ljava/lang/Class;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_retransformClass
  (JNIEnv *, jclass, jclass, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    retransformClassByName
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_retransformClassByName
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    getLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_getLoadedClasses
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    getClassByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_getClassByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    getClassBytes
 * Signature: (Ljava/lang/Class;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_getClassBytes
  (JNIEnv *, jclass, jclass);

/*
 * Class:     cn_xiaozhou233_juiceagent_api_JuiceAgent
 * Method:    getClassBytesByName
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_xiaozhou233_juiceagent_api_JuiceAgent_getClassBytesByName
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
