/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceremapper_JuiceRemapper */

#ifndef _Included_cn_xiaozhou233_juiceremapper_JuiceRemapper
#define _Included_cn_xiaozhou233_juiceremapper_JuiceRemapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    addBlacklist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_addBlacklist
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    addWhitelist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_addWhitelist
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    removeBlacklist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_removeBlacklist
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    removeWhitelist
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_removeWhitelist
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    clearBlacklist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_clearBlacklist
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceremapper_JuiceRemapper
 * Method:    clearWhitelist
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceremapper_JuiceRemapper_clearWhitelist
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
