#pragma once

#include <jni.h>
#include <jvmti.h>
#include <JuiceAgent/Logger.hpp>
#include <libagent.hpp>
#include <utils.hpp>

// Generated by JuiceAgent-API
#include <cn_xiaozhou233_juiceagent_api_JuiceAgent.h>
