/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceagent_injector_InjectorNative */

#ifndef _Included_cn_xiaozhou233_juiceagent_injector_InjectorNative
#define _Included_cn_xiaozhou233_juiceagent_injector_InjectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceagent_injector_InjectorNative
 * Method:    inject
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_injector_InjectorNative_inject__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     cn_xiaozhou233_juiceagent_injector_InjectorNative
 * Method:    inject
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceagent_injector_InjectorNative_inject__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
