/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_orangex_injector_InjectorNative */

#ifndef _Included_cn_xiaozhou233_orangex_injector_InjectorNative
#define _Included_cn_xiaozhou233_orangex_injector_InjectorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_orangex_injector_InjectorNative
 * Method:    inject
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_orangex_injector_InjectorNative_inject
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoaderNative
 * Method:    getLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoaderNative_getLoadedClasses
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
