/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceloader_JuiceLoaderNative */

#ifndef _Included_cn_xiaozhou233_juiceloader_JuiceLoaderNative
#define _Included_cn_xiaozhou233_juiceloader_JuiceLoaderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoaderNative
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoaderNative_init
  (JNIEnv *, jobject);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoaderNative
 * Method:    injectJar
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoaderNative_injectJar
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoaderNative
 * Method:    redefineClass
 * Signature: (Ljava/lang/Class;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoaderNative_redefineClass__Ljava_lang_Class_2_3BI
  (JNIEnv *, jobject, jclass, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoaderNative
 * Method:    redefineClass
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoaderNative_redefineClass__Ljava_lang_String_2_3BI
  (JNIEnv *, jobject, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
