/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_xiaozhou233_juiceloader_JuiceLoader */

#ifndef _Included_cn_xiaozhou233_juiceloader_JuiceLoader
#define _Included_cn_xiaozhou233_juiceloader_JuiceLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_init
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    injectJar
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_injectJar
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    redefineClass
 * Signature: (Ljava/lang/Class;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_redefineClass
  (JNIEnv *, jclass, jclass, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    redefineClassByName
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_redefineClassByName
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    getLoadedClasses
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_getLoadedClasses
  (JNIEnv *, jclass);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    getClassBytes
 * Signature: (Ljava/lang/Class;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_getClassBytes
  (JNIEnv *, jclass, jclass);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    getClassBytesByName
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_getClassBytesByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    retransformClass
 * Signature: (Ljava/lang/Class;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_retransformClass
  (JNIEnv *, jclass, jclass, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    retransformClassByName
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_retransformClassByName
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    getClassByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_getClassByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    nativeGetThreadByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Thread;
 */
JNIEXPORT jobject JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_nativeGetThreadByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     cn_xiaozhou233_juiceloader_JuiceLoader
 * Method:    nativeInjectJarToThread
 * Signature: (Ljava/lang/Thread;Ljava/lang/String;)Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_cn_xiaozhou233_juiceloader_JuiceLoader_nativeInjectJarToThread
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
