# BuildVersion.cmake
# function to get and set the build version

function(build_version)
    set(VERSION_FILE "${CMAKE_SOURCE_DIR}/version.txt")

    file(READ "${VERSION_FILE}" VERSION_CONTENT)

    # VERSION_MAJOR
    string(REGEX MATCH "VERSION_MAJOR=([0-9]+)" _ ${VERSION_CONTENT})
    set(PROJECT_VERSION_MAJOR ${CMAKE_MATCH_1})
    # VERSION_MINOR
    string(REGEX MATCH "VERSION_MINOR=([0-9]+)" _ ${VERSION_CONTENT})
    set(PROJECT_VERSION_MINOR ${CMAKE_MATCH_1})
    # BUILD_NUMBER
    string(REGEX MATCH "BUILD_NUMBER=([0-9]+)" _ ${VERSION_CONTENT})
    set(PROJECT_BUILD_NUMBER ${CMAKE_MATCH_1})
    if(RELEASE_BUILD)
        math(EXPR PROJECT_BUILD_NUMBER "${PROJECT_BUILD_NUMBER} + 1")
        file(WRITE "${VERSION_FILE}" 
            "VERSION_MAJOR=${PROJECT_VERSION_MAJOR}\n"
            "VERSION_MINOR=${PROJECT_VERSION_MINOR}\n"
            "BUILD_NUMBER=${PROJECT_BUILD_NUMBER}\n"
        )
    endif()

    set(PROJECT_VERSION_STRING "v${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}-b${PROJECT_BUILD_NUMBER}")

    message(STATUS "Build version: ${PROJECT_VERSION_STRING}")

    add_compile_definitions(
    PROJECT_VERSION_MAJOR=${PROJECT_VERSION_MAJOR}
    PROJECT_VERSION_MINOR=${PROJECT_VERSION_MINOR}
    PROJECT_BUILD_NUMBER=${PROJECT_BUILD_NUMBER}
    PROJECT_VERSION_STRING=\"${PROJECT_VERSION_STRING}\")
endfunction()